version: 2

project_name: caam

before:
  hooks:
    - go mod tidy
    - sh -c 'go_version=$(go env GOVERSION) && printf "{\"version\":\"%s\",\"commit\":\"%s\",\"date\":\"%s\",\"go_version\":\"%s\"}\n" "{{ .Version }}" "{{ .FullCommit }}" "{{ .Date }}" "$go_version" > release-manifest.json'

builds:
  - id: caam
    main: ./cmd/caam
    binary: caam
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/Dicklesworthstone/coding_agent_account_manager/internal/version.Version={{.Version}}
      - -X github.com/Dicklesworthstone/coding_agent_account_manager/internal/version.Commit={{.ShortCommit}}
      - -X github.com/Dicklesworthstone/coding_agent_account_manager/internal/version.Date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "SHA256SUMS"

signs:
  - id: checksum
    cmd: cosign
    signature: "${artifact}.sig"
    args:
      - "sign-blob"
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: Dicklesworthstone
    name: coding_agent_account_manager
  draft: false
  prerelease: auto
  extra_files:
    - glob: release-manifest.json

# Homebrew tap publishing
brews:
  - name: caam
    repository:
      owner: Dicklesworthstone
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/Dicklesworthstone/coding_agent_account_manager
    description: "CLI tool for managing AI coding agent accounts and configurations"
    license: "MIT"
    install: |
      bin.install "caam"
      generate_completions_from_executable(bin/"caam", "completion")
    test: |
      system "#{bin}/caam", "--version"
    caveats: |
      To get started with caam:
        caam list              # List configured accounts
        caam switch <account>  # Switch to an account
        caam add               # Add a new account

# Scoop bucket publishing
scoops:
  - name: caam
    repository:
      owner: Dicklesworthstone
      name: scoop-bucket
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/Dicklesworthstone/coding_agent_account_manager
    description: "CLI tool for managing AI coding agent accounts and configurations"
    license: MIT
